## importing libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split

## Loading the dataset

In [ ]:
df=pd.read_csv("/content/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

## Handling the missing value

In [ ]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.mean())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

## Split data into train and test

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(df[['area','bedrooms','age']],df.price , test_size=0.2 ,random_state = 0)

## Create object of LinearRegression

In [ ]:
mymodel = linear_model.LinearRegression()
mymodel.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
mymodel.predict(X_test)

array([608500., 519850.])

In [ ]:
mymodel.coef_

array([    236.25, -175125.  ,  -19125.  ])

In [ ]:
mymodel.intercept_

843624.999999999

In [ ]:
 #y = m1x1 + m2x2 +m3x3 +c
y=(236.25 * 3600) +(-175125 * 3) +(-19125 * 30) + 843624.999999999
y

594999.999999999

In [ ]:
mymodel.predict([[3600,3,30]])

array([595000.])

In [ ]:
mymodel.predict([[5000,4,30]])

array([750625.])

### Finding error rate

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error([595000],[595000], squared=False)

0.0